version: '3.8'
services:
  db-dev:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: menu_booking
    networks:
      - booking
networks:
  booking:
